blank_issues_enabled: false
contact_links:
  - name: ğŸ“¢ è·å–å¸®åŠ©
    about: æå‡ºæ‚¨é‡åˆ°çš„æ‰€æœ‰æœ‰å…³ä½¿ç”¨ä¸Šçš„é—®é¢˜ã€‚æ¯”å¦‚ï¼šä¸æ¸…æ¥šä½¿ç”¨æ–¹æ³• (å¯ä»¥å…ˆçœ‹çœ‹é¦–é¡µ README)ã€æ— æ³•ç†è§£æŸäº›åŠŸèƒ½çš„å«ä¹‰ç­‰
    url: https://github.com/WangHaonie/PlainCEETimer/discussions/new/choose